CREATE TABLE GROCERIES(
  GROCERIES_ID INT(10) AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  SELLING_PRICE DECIMAL(10,2)
);

CREATE TABLE GROCERIES_BOUGHT_BY_CUSTOMERS (
  GBBC_ID INT(10) AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT(10) NOT NULL,
  GROCERIES_ID INT(10) NOT NULL,
  QUANTITY INT(10) NOT NULL,
  PRICE DECIMAL(10,2),
  DATE DATE NOT NULL,

  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID),
  FOREIGN KEY (GROCERIES_ID) REFERENCES GROCERIES (GROCERIES_ID)
)